### ISSUE TITLE
Remove/Disable Ores?

### ISSUE THREAD

**Issue by Saphirius** [cScotPlay/BasicNetherOres#45]
Im trying to make my own Modpack, where theres as little clutter as possible. For example i made all Copper Recipes use tconstruct copper, and then completely removed Copper Ingots, Nuggets and Blocks from Jei, so its easier to navigate. Now sadly a few mods interact in a way, that adds loads of clutter. Because BNO adds Tin, suddenly Mystical Agriculture adds Tin seeds, TCon adds molten tin, molten tin bucket, molten tin capsule etc. Also ex nihilo suddenly shows tin and zinc ore pieces and chunks in jei. So loads of recipes and stuff, even though theres not a single use for tin in the pack, and theres no zinc. Now i tried hiding the molten tin through craft tweaker but i cant get that to work. Is there a way to simply remove Tin from BNO? Can be as drastic as deleting some lines form the .jar itself.

Apart from that big thanks for the mod, its quite simple, but very well done and perfect for a lot of packs.

**Comment by cScotPlay** [comment]
I wish there were a better way to turn on and off the registration of blocks and items.  Due to the way Forge requests us to register items and blocks it's nearly impossible to turn off the registration.  One way we fixed this in our modpack was to use [https://www.curseforge.com/minecraft/mc-mods/auto-ore-dictionary-converter](https://www.curseforge.com/minecraft/mc-mods/auto-ore-dictionary-converter).  This helped us do what you're asking for.  We still had to remove some items from JEI, but it wasn't bad once this was set.  Hope this helps a bit.
