### ISSUE TITLE
[1.19-Forge] Config file not working. (Disabling ores doesn't actually disable them).

### ISSUE THREAD

**Issue by Gbergz** [cScotPlay/BasicNetherOres#46]
Title^

Tried to disable some bno ores, Osmium, Zinc etc. But they're still generating even when disabled.
Config is not working.

Minecraft: 1.19
Forge: 41.0.63
BNO: 8.0.1

Edit: I think the whole config is not working, veinSize, minHeight etc. Just wanna add that aswell.

**-** Gbergz

**Comment by cScotPlay** [comment]
You are correct.  The config file isn't working and probably won't work going forward with the use of JSON files.  I added a couple of datapacks that you can edit to get the configs you would like.  Due to the way that features are now dealt with I don't know if the config will actually work.  A future update will remove most of the data from the config.  Sorry, wish I had better news on the config file.

**Comment by Gbergz** [comment]
Gotcha, I used KubeJS to remove those I wanted to disable. Worked fine.
Rarity on the ores though, are those in datapacks?

Edit: Found them in the datapacks. Will edit them

Thanks for answers!

**Comment by cScotPlay** [comment]
Glad things worked.  Really glad to hear the KubeJS is working for all the datapack updates.

**Comment by allanonmage** [comment]
Where are the datapack(s)?
